/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.Koneksi;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
/**
 *
 * @author dr. Yoe
 */
public class FramePegawaiPns extends javax.swing.JFrame {
    
    private Koneksi CRUD;

    /**
     * Creates new form FramePegawaiPns
     */
    public FramePegawaiPns() {
        CRUD = new Koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void reset() {
        txtid.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txtnip.setText(null);
        txtpangkat.setText(null);
        txtjabatan.setText(null);
        txtunit_organisasi.setText(null);
        txtfoto.setText(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpangkat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtjabatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtunit_organisasi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfoto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama");

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat");

        jLabel4.setText("Nip");

        jLabel5.setText("Pangkat");

        jLabel6.setText("Jabatan");

        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });

        jLabel7.setText("Unit_organisasi");

        jLabel8.setText("Foto");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("INPUT DATA PEGAWAI PNS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Alamat", "Nip", "Pangkat", "Jabatan", "Unit_organisasi", "Foto"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtunit_organisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(201, 201, 201))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtunit_organisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if (
                txtid.getText().trim().equals("") && 
                txtnama.getText().trim().equals("") &&
                txtalamat.getText().trim().equals("")&&
                txtnip.getText().trim().equals("")&&
                txtpangkat.getText().trim().equals("")&&
                txtjabatan.getText().trim().equals("")&&
                txtunit_organisasi.getText().trim().equals("")&&
                txtfoto.getText().trim().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Data yang anda masukan belum lengkap");
        } else {
            model.addRow(new Object[]{txtid.getText(), txtnama.getText(),txtalamat.getText(), txtnip.getText(), txtpangkat.getText(), txtjabatan.getText(), txtunit_organisasi.getText(), txtfoto.getText()});
            JOptionPane.showMessageDialog(this, "Anda berhasil memasukan data");
        }
        reset();        
        
        /*try {
            if(txtid.getText().equals("")){
                JOptionPane.showMessageDialog(this, "id belum diisi");
                txtid.requestFocus();
            } else if (txtnama.getText().equals("")){
                JOptionPane.showMessageDialog(this, "nama belum diisi");
                txtnama.requestFocus();
            } else if (txtalamat.getText().equals("")){
                JOptionPane.showMessageDialog(this, "alamat belum diisi");
                txtalamat.requestFocus();
            } else if (txtnip.getText().equals("")){
                JOptionPane.showMessageDialog(this, "nip belum diisi");
                txtnip.requestFocus();
            } else if (txtpangkat.getText().equals("")){
                JOptionPane.showMessageDialog(this, "pangkat belum diisi");
                txtpangkat.requestFocus();
            } else if (txtjabatan.getText().equals("")){
                JOptionPane.showMessageDialog(this, "jabatan belum diisi");
                txtjabatan.requestFocus();
            } else if (txtunit_organisasi.getText().equals("")){
                JOptionPane.showMessageDialog(this, "unit_organisasi belum diisi");
                txtunit_organisasi.requestFocus();
            } else if (txtfoto.getText().equals("")){
                JOptionPane.showMessageDialog(this, "foto belum diisi");
                txtfoto.requestFocus();
            } else {
                CRUD.simpanPegawai_Pns(txtid.getText(), txtnama.getText(), txtalamat.getText(),txtnip.getText(), txtpangkat.getText(), txtjabatan.getText(), txtunit_organisasi.getText(), txtfoto.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        if (jTable1.getSelectedRow()==-1){
            if (jTable1.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam table");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }
        reset();
    }
        /*try {
            if (
                 txtid.getText().equals("") && 
                    txtnama.getText().equals("") &&
                    txtalamat.getText().equals("")&&
                    txtnip.getText().equals("")&&
                    txtpangkat.getText().equals("")&&
                    txtjabatan.getText().equals("")&&
                    txtunit_organisasi.getText().equals("")&&
                    txtfoto.getText().equals("")
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid.requestFocus();
            } else {
                CRUD.hapusPegawai_Kontrak(txtid.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                txtid.setText(null);
                txtnama.setText(null);
                txtalamat.setText(null);
                txtnip.setText(null);
                txtpangkat.setText(null);
                txtjabatan.setText(null);
                txtunit_organisasi.setText(null);
                txtfoto.setText(null);
            }
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        /*try {
        String sql = "SELECT * FROM pegawai pns WHERE id = '"+txtid.getText()+"'";
        Statement perintah = CRUD.koneksidb.createStatement();
        ResultSet data = perintah.executeQuery(sql);
        if (data.next()){
            txtnama.setText(data.getString("Nama"));
            txtalamat.setText(data.getString("Alamat"));
            txtnip.setText(data.getString("Nip"));
            txtpangkat.setText(data.getString("Pangkat"));
            txtjabatan.setText(data.getString("Jabatan"));
            txtunit_organisasi.setText(data.getString("Unit_organisasi"));
            txtfoto.setText(data.getString("Foto"));
        } else {
            txtnama.setText(null);
            txtalamat.setText(null);
            txtnip.setText(null);
            txtpangkat.setText(null);
            txtjabatan.setText(null);
            txtunit_organisasi.setText(null);
            txtfoto.setText(null);
        }
       
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }*/
    }//GEN-LAST:event_txtidKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        if (jTable1.getSelectedRow()==-1){
            if (jTable1.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam table");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
            }
        } else {
            model.setValueAt(txtid.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(txtnama.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(txtalamat.getText(), jTable1.getSelectedRow(), 2);
            model.setValueAt(txtnip.getText(), jTable1.getSelectedRow(), 3);
            model.setValueAt(txtpangkat.getText(), jTable1.getSelectedRow(), 4);
            model.setValueAt(txtjabatan.getText(), jTable1.getSelectedRow(), 5);
            model.setValueAt(txtunit_organisasi.getText(), jTable1.getSelectedRow(), 6);
            model.setValueAt(txtfoto.getText(), jTable1.getSelectedRow(), 7);
        }
    }
        reset();
                 
        
        /*try {
            if (
                 txtid.getText().equals("") && 
                    txtnama.getText().equals("") &&
                    txtalamat.getText().equals("")&&
                    txtnip.getText().equals("")&&
                    txtpangkat.getText().equals("")&&
                    txtjabatan.getText().equals("")&&
                    txtunit_organisasi.getText().equals("")&&
                    txtfoto.getText().equals("")
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid.requestFocus();
            } else {
                CRUD.ubahPegawai_Pns(txtid.getText(), txtnama.getText(), txtalamat.getText(),txtnip.getText(), txtpangkat.getText(), txtjabatan.getText(), txtunit_organisasi.getText(), txtfoto.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "SELECT * FROM pegawai pns WHERE id = '"+txtid.getText()+"'";
        Statement perintah = CRUD.koneksidb.createStatement();
        ResultSet data = perintah.executeQuery(sql);
        if (data.next()){
            txtnama.setText(data.getString("Nama"));
            txtalamat.setText(data.getString("Alamat"));
            txtnip.setText(data.getString("Tgl_lahir"));
            txtpangkat.setText(data.getString("Pendidikan"));
            txtjabatan.setText(data.getString("Prog_studi"));
            txtunit_organisasi.setText(data.getString("Tahun_lulus"));
            txtfoto.setText(data.getString("Foto"));
        } else {
            txtnama.setText(null);
            txtalamat.setText(null);
            txtnip.setText(null);
            txtpangkat.setText(null);
            txtjabatan.setText(null);
            txtunit_organisasi.setText(null);
            txtfoto.setText(null);
        }
       
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        txtid.setText(model.getValueAt(jTable1.getSelectedRow(), 0). toString());
        txtnama.setText(model.getValueAt(jTable1.getSelectedRow(), 1). toString());
        txtalamat.setText(model.getValueAt(jTable1.getSelectedRow(), 2). toString());
        txtnip.setText(model.getValueAt(jTable1.getSelectedRow(), 3). toString());
        txtpangkat.setText(model.getValueAt(jTable1.getSelectedRow(), 4). toString());
        txtjabatan.setText(model.getValueAt(jTable1.getSelectedRow(), 5). toString());
        txtunit_organisasi.setText(model.getValueAt(jTable1.getSelectedRow(), 6). toString());
        txtfoto.setText(model.getValueAt(jTable1.getSelectedRow(), 7). toString());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiPns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiPns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiPns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiPns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePegawaiPns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpangkat;
    private javax.swing.JTextField txtunit_organisasi;
    // End of variables declaration//GEN-END:variables
}
