/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.Koneksi;
import PEGAWAI_MAIN_CLASS.Pegawai;
import PEGAWAI_VAR.PegawaiKontrak;
import PEGAWAI_VAR.PegawaiPns;
import GUI.FramePegawaiKontrak;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author dr. Yoe
 */
public class FramePegawaiKontrak extends javax.swing.JFrame {
    
    private Koneksi CRUD;

    /**
     * Creates new form FramePegawaiKontrak
     */
    public FramePegawaiKontrak() {
        CRUD = new Koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void reset() {
        txtid.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txttgl_lahir.setText(null);
        txtpendidikan.setText(null);
        txtprog_studi.setText(null);
        txttahun_lulus.setText(null);
        txtjabatan.setText(null);
        txttgl_sk.setText(null);
        txtfoto.setText(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txttgl_lahir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpendidikan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprog_studi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttahun_lulus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtjabatan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttgl_sk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfoto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Tgl_lahir");

        jLabel5.setText("Pendidikan");

        jLabel6.setText("Prog_studi");

        txttahun_lulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttahun_lulusActionPerformed(evt);
            }
        });

        jLabel7.setText("Tahun_lulus");

        jLabel8.setText("Jabatan");

        txttgl_sk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgl_skActionPerformed(evt);
            }
        });

        jLabel9.setText("Tgl_sk");

        jLabel10.setText("Foto");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("INPUT DATA PEGAWAI KONTRAK");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Alamat", "Tgl_lahir", "Pendidikan", "Prog_studi", "Tahun_lulus", "Jabatan", "Foto"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttgl_sk, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(65, 65, 65)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtprog_studi, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(txttahun_lulus)))
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttgl_lahir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprog_studi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttahun_lulus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txttgl_sk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        setBounds(0, 0, 675, 602);
    }// </editor-fold>//GEN-END:initComponents

    private void txttahun_lulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttahun_lulusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttahun_lulusActionPerformed

    private void txttgl_skActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgl_skActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgl_skActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if (
                txtid.getText().trim().equals("") && 
                txtnama.getText().trim().equals("") &&
                txtalamat.getText().trim().equals("")&&
                txttgl_lahir.getText().trim().equals("")&&
                txtpendidikan.getText().trim().equals("")&&
                txtprog_studi.getText().trim().equals("")&&
                txttahun_lulus.getText().trim().equals("")&&
                txtjabatan.getText().trim().equals("")&&
                txttgl_sk.getText().trim().equals("")&&
                txtfoto.getText().trim().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Data yang anda masukan belum lengkap");
        } else {
            model.addRow(new Object[]{txtid.getText(), txtnama.getText(),txtalamat.getText(), txttgl_lahir.getText(), txtpendidikan.getText(), txtprog_studi.getText(), txttahun_lulus.getText(), txtjabatan.getText(), txttgl_sk.getText(), txtfoto.getText()});
            JOptionPane.showMessageDialog(this, "Anda berhasil memasukan data");
        }
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
    // TODO add your handling code here:
    /*try {
        String sql = "SELECT * FROM pegawai kontrak WHERE id = '"+txtid.getText()+"'";
        Statement perintah = CRUD.koneksidb.createStatement();
        ResultSet data = perintah.executeQuery(sql);
        if (data.next()){
            txtnama.setText(data.getString("Nama"));
            txtalamat.setText(data.getString("Alamat"));
            txttgl_lahir.setText(data.getString("Tgl_lahir"));
            txtpendidikan.setText(data.getString("Pendidikan"));
            txtprog_studi.setText(data.getString("Prog_studi"));
            txttahun_lulus.setText(data.getString("Tahun_lulus"));
            txtjabatan.setText(data.getString("Jabatan"));
            txttgl_sk.setText(data.getString("Tgl_sk"));
            txtfoto.setText(data.getString("Foto"));
        } else {
            txtnama.setText(null);
            txtalamat.setText(null);
            txttgl_lahir.setText(null);
            txtpendidikan.setText(null);
            txtprog_studi.setText(null);
            txttahun_lulus.setText(null);
            txtjabatan.setText(null);
            txttgl_sk.setText(null);
            txtfoto.setText(null);
        }
       
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }*/
    }//GEN-LAST:event_txtidKeyPressed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        if (jTable1.getSelectedRow()==-1){
            if (jTable1.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam table");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
            }
        } else {
            model.setValueAt(txtid.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(txtnama.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(txtalamat.getText(), jTable1.getSelectedRow(), 2);
            model.setValueAt(txttgl_lahir.getText(), jTable1.getSelectedRow(), 3);
            model.setValueAt(txtpendidikan.getText(), jTable1.getSelectedRow(), 4);
            model.setValueAt(txtprog_studi.getText(), jTable1.getSelectedRow(), 5);
            model.setValueAt(txttahun_lulus.getText(), jTable1.getSelectedRow(), 6);
            model.setValueAt(txtjabatan.getText(), jTable1.getSelectedRow(), 7);
            model.setValueAt(txttgl_sk.getText(), jTable1.getSelectedRow(), 8);
            model.setValueAt(txtfoto.getText(), jTable1.getSelectedRow(), 9);
        }
    }
        reset();
         /*try {
            if (
                 txtid.getText().equals("") && 
                    txtnama.getText().equals("") &&
                    txtalamat.getText().equals("")&&
                    txttgl_lahir.getText().equals("")&&
                    txtpendidikan.getText().equals("")&&
                    txtprog_studi.getText().equals("")&&
                    txttahun_lulus.getText().equals("")&&
                    txtjabatan.getText().equals("")&&
                    txttgl_sk.getText().equals("")&&
                    txtfoto.getText().equals("")
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid.requestFocus();
            } else {
                CRUD.ubahPegawai_Kontrak(txtid.getText(), txtnama.getText(), txtalamat.getText(),txttgl_lahir.getText(), txtpendidikan.getText(), txtprog_studi.getText(), txttahun_lulus.getText(), txtjabatan.getText(), txttgl_sk.getText(), txtfoto.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            }
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        if (jTable1.getSelectedRow()==-1){
            if (jTable1.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam table");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }
        reset();
    }
        
        
        
                 /*try {
            if (
                 txtid.getText().equals("") && 
                    txtnama.getText().equals("") &&
                    txtalamat.getText().equals("")&&
                    txttgl_lahir.getText().equals("")&&
                    txtpendidikan.getText().equals("")&&
                    txtprog_studi.getText().equals("")&&
                    txttahun_lulus.getText().equals("")&&
                    txtjabatan.getText().equals("")&&
                    txttgl_sk.getText().equals("")&&
                    txtfoto.getText().equals("")
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid.requestFocus();
            } else {
                CRUD.hapusPegawai_Kontrak(txtid.getText());
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                txtid.setText(null);
                txtnama.setText(null);
                txtalamat.setText(null);
                txttgl_lahir.setText(null);
                txtpendidikan.setText(null);
                txtprog_studi.setText(null);
                txttahun_lulus.setText(null);
                txtjabatan.setText(null);
                txttgl_sk.setText(null);
                txtfoto.setText(null);
            }
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            try {
        String sql = "SELECT * FROM pegawai kontrak WHERE id = '"+txtid.getText()+"'";
        Statement perintah = CRUD.koneksidb.createStatement();
        ResultSet data = perintah.executeQuery(sql);
        if (data.next()){
            txtnama.setText(data.getString("Nama"));
            txtalamat.setText(data.getString("Alamat"));
            txttgl_lahir.setText(data.getString("Tgl_lahir"));
            txtpendidikan.setText(data.getString("Pendidikan"));
            txtprog_studi.setText(data.getString("Prog_studi"));
            txttahun_lulus.setText(data.getString("Tahun_lulus"));
            txtjabatan.setText(data.getString("Jabatan"));
            txttgl_sk.setText(data.getString("Tgl_sk"));
            txtfoto.setText(data.getString("Foto"));
        } else {
            txtnama.setText(null);
            txtalamat.setText(null);
            txttgl_lahir.setText(null);
            txtpendidikan.setText(null);
            txtprog_studi.setText(null);
            txttahun_lulus.setText(null);
            txtjabatan.setText(null);
            txttgl_sk.setText(null);
            txtfoto.setText(null);
        }
       
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); {
        txtid.setText(model.getValueAt(jTable1.getSelectedRow(), 0). toString());
        txtnama.setText(model.getValueAt(jTable1.getSelectedRow(), 1). toString());
        txtalamat.setText(model.getValueAt(jTable1.getSelectedRow(), 2). toString());
        txttgl_lahir.setText(model.getValueAt(jTable1.getSelectedRow(), 3). toString());
        txtpendidikan.setText(model.getValueAt(jTable1.getSelectedRow(), 4). toString());
        txtprog_studi.setText(model.getValueAt(jTable1.getSelectedRow(), 5). toString());
        txttahun_lulus.setText(model.getValueAt(jTable1.getSelectedRow(), 6). toString());
        txtjabatan.setText(model.getValueAt(jTable1.getSelectedRow(), 7). toString());
        txttgl_sk.setText(model.getValueAt(jTable1.getSelectedRow(), 8). toString());
        txtfoto.setText(model.getValueAt(jTable1.getSelectedRow(), 9). toString());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiKontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiKontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiKontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePegawaiKontrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePegawaiKontrak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txtprog_studi;
    private javax.swing.JTextField txttahun_lulus;
    private javax.swing.JTextField txttgl_lahir;
    private javax.swing.JTextField txttgl_sk;
    // End of variables declaration//GEN-END:variables
}
